### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by OldNo7** [cbordeman/Mvvm-Tools#1]
If I have file open with a View or ViewModel ending (i.e. _FooView.xaml_, _FooViewModel.cs_, etc) I get the following error:

```
The type initializer for 'MvvmTools.Utilities.SettingsUtilities' threw an exception.
```

When I tried "Tools->Options->MVVM Tools" I get: 

```
An error occurred loading this property page
```

If I open a file that doesn't have View or ViewModel in the name I get the expected error dialog that says: 

```
Couldn't find any matching view or view model classes
```

I would love to use this extention. It would be very usefull, If I can get it to work. I'm using Visual Studio 2013 With Caliburn.Micro.

**Comment by cbordeman** [comment]
Try installing .Net  4.6.  Please let me know if that solves it.

 

Chris Bordeman

**Comment by cbordeman** [comment]
Any luck?

**Comment by cbordeman** [comment]
I know if you install the VS2015 RC it will work (in 2013). I'm currently targeting all the way back to 2010, which may be not be worth it due to confusion around dependencies.

I'll issue an update in a few days to correct the dependencies.

**Comment by OldNo7** [comment]
I tried installing 4.6 from here:
https://msdn.microsoft.com/en-us/library/w0x726c2(v=VS.110).aspx
Still doesn't work. I'll try the VS2015 RC when I get a chance.

**Comment by cbordeman** [comment]
Thanks.

**Comment by cbordeman** [comment]
What version of Visual Studio are you using?

**Comment by cbordeman** [comment]
Sorry, just saw you're on VS2013.

**Comment by cbordeman** [comment]
I'll issue an update in a few days to correct the dependencies.

**Comment by cbordeman** [comment]
OldNo7, I'm issuing an update soon so you can configure the suffixes for the views and view models.  For example, if you use SamplePresentationModel for the view model within one project or several, you can configure that.  Also, you can configure the list of recognized view suffixes.

If your view models or views aren't named with a special suffix at all, the extension has no way of telling them apart from regular classes.  And I'd rather not resort to looking for particular inheritance as property notification can be done many ways.

**Comment by OldNo7** [comment]
My views and view models are in the same project and same namespace. They are named using the default convention used by Caliburn.micro. 

```
AppView.xaml 
AppViewModel.cs
```

They are both in the same directory although I've also tried having them in separate directories ("Views" and "ViewModels")

**Comment by cbordeman** [comment]
Please answer these questions:
1) have you installed VS2015 RC yet?
2  Are you able to access the Options page yet?  If that doesn't open maybe the plugin won't work at all.
3) From the view model, press the Ctrl+E, Ctrl+V.  What exactly happens?

I've tested your scenario and it worked (on my computer (famous lasts), so if you _can_ see options, is there a chance you could put your project up on One Drive or DropBox and post a link?  If necessary, encrypt it and email me the password through github or cbordeman@outlook.com.  I really want this thing to work for you!!

**Comment by OldNo7** [comment]
1) I'm downloading 2015 now.
2) No I can't access Options. I get this error:
![screenshot](https://cloud.githubusercontent.com/assets/2074377/8806788/2c2853b4-2f8d-11e5-92ea-57a9348eab22.png)

3) I get the following error
![screenshot](https://cloud.githubusercontent.com/assets/2074377/8806717/d65f3f2e-2f8c-11e5-9780-d1acc1486215.png)

**Comment by OldNo7** [comment]
After installing Visual Studio 2015 it now works in VS2013

**Comment by cbordeman** [comment]
Great thanks.
