### ISSUE TITLE
How to configure naming convention

### ISSUE THREAD

**Issue by BradleyUffner** [cbordeman/Mvvm-Tools#2]
I use a naming pattern where Windows have a "Windows" suffix, and the view-model has a "VM" suffix, for example "MainWindow", and "MainWindowVM".  I'm unable to figure out how to configure this pattern in your tool.

General Settings: https://imgur.com/a/ZTUxq
Solution and Projects Settings: https://imgur.com/a/3PxC2

When I am in the view-model, trying to navigate to the view opens a dialog making me choose from "MainWindow.xmal", or "MainWindow.xaml.cs" (shouldn't navigating to the view only show xaml files?).

When I am in the view, trying to switch to the view-model just gives the error "Couldn't find any matching views or view models".

Is it possible for me to make my pattern work with your extension?

**Comment by cbordeman** [comment]
Sorry I didn't see this till now.  What you've configured should work, but doesn't.  This is a bug.

**Comment by cbordeman** [comment]
OK, fixed in version 0.2.0.6.  Let me know if this works for you.
