### ISSUE TITLE
Package did not load correctly

### ISSUE THREAD

**Issue by mathikp** [cbordeman/Mvvm-Tools#4]
I'm getting this error while switch between View and ViewModel. I tried uninstall and reinstall the VSIX again. Still facing same issue. I'm using VS 2017. ActivityLog file attached. [ActivityLog.zip](https://github.com/cbordeman/Mvvm-Tools/files/2929929/ActivityLog.zip)

![image](https://user-images.githubusercontent.com/13851265/53791171-c49af780-3f4e-11e9-8d68-dccdde4cb8c8.png)

**Comment by cbordeman** [comment]
Sorry, KP, I checked in a version that works in 2019, now I’ve broken compatibility with 2017.  I’ve got my references all screwed up.  I will post an update as soon as possible.

Chris Bordeman

**Comment by cbordeman** [comment]
Sorry to users unable to use MVVM Tools for VS2017 during this time.  I'm rebuilding the solution and having to split my time between my day job, learning Unity 3D, and this.  Frankly, Unity is way more fun.

**Comment by cbordeman** [comment]
Fixed.  Only two years later.

**Comment by mathikp** [comment]
@cbordeman  I cannot install Mvvm Tools into my Visual Studio Professional 2017 now :(. Did you remove VS 2017 support?

**Comment by cbordeman** [comment]
Sorry, yes, please stick with the older VSIX.  This version fixes early load issues specific to VS2019 but is incompatible with 2017 and earlier.  I'll generate the old release and post it in a Releases folder and put it in the Marketplace under "Mvvm Tools for 2017."
