### ISSUE TITLE
"Please load a solution" Error while in a solution

### ISSUE THREAD

**Issue by mzhukovs** [cbordeman/Mvvm-Tools#5]
Using latest version of VS2019 Enterprise, I get this when I go to the "Solutions and Projects" options page for the extension MVVM Tools:
![image](https://user-images.githubusercontent.com/13161978/59692449-841e6b80-9217-11e9-9b6e-154163c806c6.png)

Even though I have a solution open. Tried with a few different solutions and same result each time. Any ideas?

And the functionality does not work, Ctrl E,V is indeed assigned to MVVM Tools shortcut but does nothing, presumably because of the aforementioned.

Any help would be appreciated. Thank you.

**Comment by kmgallahan** [comment]
Same problem here.

**Comment by cbordeman** [comment]
This issue was related to VS2019's async extension loading.  It's been fixed.
