### ISSUE TITLE
Great idea, but possible expansion to non xaml/wpf?

### ISSUE THREAD

**Issue by ryantheleach** [cbordeman/Mvvm-Tools#6]
Navigating around MVVM like this is an excellent idea, but at the moment the configuration (seems) needlessly constrained to only C# / xaml projects.

I was looking for something like this, but for Kendo/Javascript MVVM projects.

I suspect a little flexibility with the configuration would enable this to work on more projects.

**Comment by cbordeman** [comment]
No plans for that, no.
