### ISSUE TITLE
Add Support for Subfolders?

### ISSUE THREAD

**Issue by drepamig** [cbordeman/Mvvm-Tools#7]
Hello. Thanks for making this extension!

I have my project organized such that my viewmodels and views are organized by "screen". Example:

projectroot/Views/ScreenA/[many views]
projectroot/ViewModels/ScreenA/[many viewmodels]
projectroot/Views/ScreenB/[many views]
projectroot/ViewModels/ScreenB/[many viewmodels]

Doing it this way, I can't seem to get the extension to find the corresponding View or ViewModel. Is there any way to get this to work with this folder structure? 

For what it's worth, I use Stylet as my MVVM framework and that package looks for the corresponding View/ViewModel by taking the current path of the V/VM and replacing the word "View" with "ViewModel" (and vise versa) and looking in that directory. That method seems to work well.

**Comment by cbordeman** [comment]
HAve you tried the Tools -> Options -> MVVM Tools pages?  You can turn off automatic searching an configure a solution level strategy.  You can also override this per project if other project to stick to the plan.

I don't recall if the config is flexible enough, but if it doesn't work, send me a sample project and I'll add the functionality.  You could also fork the project and send me a pull request.

BTW, doing this usually allows the plugin to locate the class far more quickly compared to the generic approach of scanning every class in the solution, especially for medium and large solutions.

**Comment by cbordeman** [comment]
Please provide a sample project and I will implement.

**Comment by drepamig** [comment]
Sorry for the radio silence on this issue. I started making a sample project to demonstrate what's happening and found the root (I think) of the issue. The MVVM framework that I'm using ([Stylet](https://github.com/canton7/Stylet)) strongly [suggests deleting the automatically generated [viewname].xaml.cs file](https://github.com/canton7/Stylet/wiki/ViewModel-First#delete-the-code-behind), which I've done for my actual project. When making the sample, I realized I left one codebehind in place and the other was deleted. Your extension is able to find the matching View/ViewModel when in _include_ the codebehind. It can't find the View/ViewModel when the codebehind is _not_ included.

I've attached the project that demonstrates this.
[WpfApp1.zip](https://github.com/cbordeman/Mvvm-Tools/files/6305125/WpfApp1.zip)

**Comment by cbordeman** [comment]
The extension uses the CodeDom to get the classes, which means the code behind must exist.  I don't think there's anything that can be done about this other that to avoid the incorrect advice that framework advice gives.  

Looking at the link you posted, it is wrong to suggest you can delete the code behind at no loss of functionality.  Code behind is actually _extremely_ useful for doing UI specific stuff that can't be done elsewhere without a ton of extra code since it's got direct access to the UI.  Just because you no longer need it to create VMs is absolutely no reason to delete that.
