### ISSUE TITLE
Not compatible with VS 2022

### ISSUE THREAD

**Issue by Grahamvs** [cbordeman/Mvvm-Tools#8]
As the title says, it's not compatible with VS 2022 even though it states it is.

Please see the following [link](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) for help on porting the extension.

**Comment by hqqdnlkemf3453** [comment]
I also encountered this error.

**Comment by cbordeman** [comment]
Should work as of.  In v5 I also made the "go to view / viewmodel" vastly quicker (for larger solutions) by checking filenames before parsing each file.  However, it only works if your filenames match the containing class.  Will make this an option in the future, but I think it's a somewhat safe bet these days.
